import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        secondary: "#0058be",
        "secondary-fixed-dim": "#adc6ff",
        "primary-container": "#131b2e",
        "on-tertiary": "#ffffff",
        primary: "#000000",
        surface: "#f8f9ff",
        "on-secondary-container": "#fefcff",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-container": "#818486",
        "inverse-primary": "#bec6e0",
        "surface-container-high": "#dce9ff",
        "on-primary-fixed": "#131b2e",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c4c7c9",
        "surface-variant": "#d3e4fe",
        "inverse-on-surface": "#eaf1ff",
        outline: "#76777d",
        "on-surface-variant": "#45464d",
        "surface-container": "#e5eeff",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed-variant": "#444749",
        "secondary-fixed": "#d8e2ff",
        on: {
          surface: "#0b1c30",
          background: "#0b1c30"
        },
        background: "#f8f9ff",
        "tertiary-container": "#191c1e",
        "on-secondary-fixed": "#001a42",
        "surface-dim": "#cbdbf5",
        "on-error-container": "#93000a",
        "on-primary-container": "#7c839b",
        "primary-fixed-dim": "#bec6e0",
        "surface-tint": "#565e74",
        tertiary: "#000000",
        "on-secondary-fixed-variant": "#004395",
        "on-tertiary-fixed": "#191c1e",
        error: "#ba1a1a",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#2170e4",
        "tertiary-fixed": "#e0e3e5",
        "on-error": "#ffffff",
        "primary-fixed": "#dae2fd",
        "outline-variant": "#c6c6cd",
        "on-secondary": "#ffffff",
        "inverse-surface": "#213145",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        xs: "4px",
        md: "16px",
        lg: "24px",
        gutter: "20px",
        "container-padding": "40px",
        xl: "32px",
        base: "4px",
      },
      fontFamily: {
        "label-caps": ["Inter"],
        h2: ["Manrope"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "mono-data": ["Inter"],
        h1: ["Manrope"],
        "stats-lg": ["Manrope"],
      },
    },
  },
  plugins: [],
};
export default config;
